
version: 2

models:
  - name: report_new_users_last_30days
    description: "A report that shows the users that joined in the last 30 days"
    columns:
      - name: id
        description: "The primary key for the users table"
        data_type: INT64
      - name: name
        description: "The name of the user"
        data_type: STRING
      - name: registration_date
        description: "The date when the user registered"
        data_type: DATE
      - name: email
        description: "The email of the user"
        data_type: STRING

  - name: report_user_activity_summary
    description: "A report that combines data from all tables to get a total view of the user's infos"
    columns:
      - name: id
        description: "The primary key for the users table"
        data_type: INT64
      - name: name
        description: "The name of the user"
        data_type: STRING
      - name: registration_date
        description: "The date when the user registered"
        data_type: DATE
      - name: email
        description: "The email of the user"
        data_type: STRING
      - name: preference_version
        description: "The version of the preference"
        data_type: INT64
      - name: is_latest_preference
        description: "Shows if that's the latest preference version"
        data_type: BOOL
      - name: preferred_language
        description: "The user's prefered language"
        data_type: STRING
      - name: notifications_enabled
        description: "Shows if the user has enabled notifications"
        data_type: BOOL
      - name: marketing_opt_in
        description: "Shows if the user has opted in on marketing communication"
        data_type: BOOL
      - name: user_preferences_created_at
        description: "The timestamp when the user preference was created"
        data_type: TIMESTAMP
      - name: user_preferences_updated_at
        description: "The timestamp when the user preference was last updated"
        data_type: TIMESTAMP

  - name: report_user_daily_transactions
    description: "A report that shows user's daily transactions"
    columns:
      - name: user_id
        description: "The primary key for the users table"
        data_type: INT64
      - name: transaction_date
        description: "The date the transaction"
        data_type: DATE
      - name: total_deposit
        description: "The total deposit transaction amount"
        data_type: NUMERIC
      - name: total_withdrawl
        description: "The total withdrawl transaction amount"
        data_type: NUMERIC

  - name: report_user_latest_preferences
    description: "A report that shows user's latest preferences"
    columns:
      - name: id
        description: "The primary key for the users table"
        data_type: INT64
      - name: name
        description: "The name of the user"
        data_type: STRING
      - name: registration_date
        description: "The date when the user registered"
        data_type: DATE
      - name: email
        description: "The email of the user"
        data_type: STRING
      - name: total_deposit
        description: "The total deposit transaction amount for that user"
        data_type: NUMERIC
      - name: total_withdrawl
        description: "The total withdrawl transaction amount for that user"
        data_type: NUMERIC
      - name: total_balance
        description: "The total balance transaction amount"
        data_type: NUMERIC
      - name: preferred_language
        description: "The user's prefered language"
        data_type: STRING
      - name: notifications_enabled
        description: "Shows if the user has enabled notifications"
        data_type: BOOL
      - name: marketing_opt_in
        description: "Shows if the user has opted in on marketing communication"
        data_type: BOOL
      - name: user_preferences_created_at
        description: "The timestamp when the user preference was created"
        data_type: TIMESTAMP
      - name: user_preferences_updated_at
        description: "The timestamp when the user preference was last updated"
        data_type: TIMESTAMP
