
version: 2

models:
  - name: users
    description: "This table contain the user's information"
    columns:
      - name: id
        description: "The primary key for the users table"
        data_type: INT64
        data_tests:
          - unique
          - not_null
      - name: name
        description: "The name of the user"
        data_type: STRING
      - name: registration_date
        description: "The date when the user registered"
        data_type: DATE
      - name: email
        description: "The email of the user"
        data_type: STRING

  - name: user_preferences
    description: "This table contain the user's preferences"
    columns:
      - name: id
        description: "The primary key for the user_preferences table"
        data_type: INT64
        data_tests:
          - unique
          - not_null
      - name: user_id
        description: "The user ID that has these preferences"
        data_type: INT64
        data_tests:
          - not_null
      - name: preferred_language
        description: "The user's prefered language"
        data_type: STRING
      - name: notifications_enabled
        description: "Shows if the user has enabled notifications"
        data_type: BOOL
      - name: marketing_opt_in
        description: "Shows if the user has opted in on marketing communication"
        data_type: BOOL
      - name: created_at
        description: "The timestamp when the user preference was created"
        data_type: TIMESTAMP
      - name: updated_at
        description: "The timestamp when the user preference was last updated"
        data_type: TIMESTAMP

  - name: transactions
    description: "This table contain the user's preferences"
    columns:
      - name: id
        description: "The primary key for the transactions table"
        data_type: INT64
        data_tests:
          - unique
          - not_null
      - name: user_id
        description: "The user ID that was part of the transaction"
        data_type: INT64
        data_tests:
          - not_null
      - name: transaction_date
        description: "The date of the transaction"
        data_type: DATE
      - name: amount
        description: "The transaction amount"
        data_type: FLOAT64
      - name: type
        description: "The transaction type"
        data_type: STRING
        data_tests:
          - accepted_values:
              values: ['deposit', 'withdrawal']
